version: "3"

services:
    # The application
    form-app:
      build: .
      ports:
        - 3000:3000
      volumes:
        - ./src:/opt/app/src
      environment:
        - PORT=3000
        - DATABASE=postgres://postgres:secret@form-postgres:5432/form
      depends_on:
        - form-postgres
    # Database server
    form-postgres:
      image: postgres:10-alpine
      environment:
        - POSTGRES_PASSWORD=secret
        - POSTGRES_DB=form
      logging:
        driver: none
    form-adminer:
      image: adminer
      ports:
        - 8080:8080